<?php
	global $_CONFIG;
?>

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<link rel="stylesheet" href="<?php echo $_CONFIG->css_path; ?>admin/global.css" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="<?php echo $_CONFIG->css_path; ?>admin/dropzone.css" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="<?php echo $_CONFIG->css_path; ?>admin/skeleton/skeleton.css" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="<?php echo $_CONFIG->css_path; ?>admin/skeleton/layout.css" type="text/css" media="screen" charset="utf-8">
<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<title>Log</title>
</head>
<body>

  