<?  global $config; ?>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="js/jquery.validate.min.js" charset="utf-8"></script>
<script src="js/jquery.form.js" charset="utf-8"></script>
<script src="js/site.js" charset="utf-8"></script>
<script src="js/ajax.js" charset="utf-8"></script>
<script>
	<?php echo $config['extra_js'];?>
</script>
</body>
</html>