<?php 
global $_CONFIG;
global $page; 
?>

<script type="text/javascript" src="<?php echo $_CONFIG->js_path; ?>jquery.min.js"></script>
<script src="<? echo $_CONFIG->js_path; ?>dropzone.min.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $_CONFIG->js_path; ?>admin.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $_CONFIG->js_path; ?>jquery.validate.min.js"></script>
<script type="text/javascript" src="<?php echo $_CONFIG->js_path; ?>jquery.form.js"></script> 
<script type="text/javascript" src="<?php echo $_CONFIG->js_path; ?>admin_ajax.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $_CONFIG->js_path; ?>responsive-tables.js"></script>
<script type="text/javascript" src="<?php echo $_CONFIG->js_path; ?>wysiwyg/js/froala_editor.min.js"></script>
<script type="text/javascript" src="<?php echo $_CONFIG->js_path; ?>jquery.cookie.js" charset="utf-8"></script>

</body>
</html>