<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="../admin/js/site.js" charset="utf-8"></script>
<script type="text/javascript" src="../admin/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="../admin/js/jquery.form.js"></script> 
<script type="text/javascript" src="../admin/js/ajax.js" charset="utf-8"></script>

</body>
</html>