<div id="content">
<h1>Admin Panel</h1>

<p>Please, Log in.</p>

<form id="login_form" action="?" method="POST">

<label for="username">Username:</label>

	<input type="text" name="username" id="username" maxlength="20" size="20" class="required"/><br/>

	
<label for="password">Password:</label>

	<input type="password" name="password" id="password" maxlength="20" size="20" class="required"/><br/>
	
<p class="feedback_text"></p>
<input type="submit"/>

</form>
</div>